version: "1"
services:
  node_dev_env:
    build: .
    container_name: node_env
    ports:
      - 8080:3000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/home/app
