version: "1"
services:
  node_dev_env:
    build: .
    container_name: node_env
    ports:
      - 8080:3000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/home/app

# TO CREATE AND RUN THE DOCKER COMPOSE CONTAINER:
#   - docker-compose up -d
# TO ONLY CREATE THE DOCKER COMPOSE CONTAINER:
#   - docker-compose create
# TO DISPOSE OF THE DOCKER COMPOSE CONTAINER:
#   - docker-compose down
# TO START THE CREATED DOCKER COMPOSE CONTAINER:
#   - docker-compose start
# TO STOP THE CREATED DOCKER COMPOSE CONTAINER:
#   - docker-compose stop
# TO ACCESS THE CREATED DOCKER COMPOSE CONTAINER VIA BASH:
#   - docker-compose exec node_dev_env bash
